$Filepath = "C:\Users\vlads\Documents\Универ\СПО\lab5.txt"
"Task 1" > "lab5.txt"
Test-Connection -ComputerName (hostname) -Count 1  | Select IPV4Address >> "lab5.txt"
$nic = gwmi -computer . -class "win32_networkadapterconfiguration"
"Client Mask: $($nic.ipsubnet | select-object -first 1)" >> "lab5.txt"
"Gateway: $($nic.DefaultIPGateway | Select-Object -Last 1)" >> "lab5.txt"
Write-Output "Task 1 Done"
"Task 2" >> "lab5.txt"
Getmac >> "lab5.txt"
Write-Output "Task 2 Done"
"Task 3" >> "lab5.txt"
ipconfig /all >> "lab5.txt"
ping www.gigabyte.com >> "lab5.txt"
Write-Output "Task 3 Done"
"Task 4" >> "lab5.txt"
ping 192.168.100.1  >> "lab5.txt"
ping www.gigabyte.com >> "lab5.txt"
Write-Output "Task 4 Done"
"Task 5" >> "lab5.txt"
Get-CimInstance -class Win32_PerfFormattedData_Tcpip_NetworkInterface >> "lab5.txt"
Write-Output "Task 5 Done"
"Task 6" >> "lab5.txt"
ping -n 1 -r 3 www.gigabyte.com >> "lab5.txt"
Write-Output "Task 6 Done"
"Task 7" >> "lab5.txt"
tracert www.gigabyte.com >> "lab5.txt"
Write-Output "Task 7 Done"
"Task 8" >> "lab5.txt"
pathping www.gigabyte.com -w 1000 >> "lab5.txt"
Write-Output "Task 8 Done"
"Task 9" >> "lab5.txt"
arp -a >> "lab5.txt"
Write-Output "Task 9 Done"
"Task 10" >> "lab5.txt"
netstat >> "lab5.txt"
Write-Output "Task 10 Done"
"Task 11" >> "lab5.txt"
ping www.gigabyte.com -f -l 1452 >> "lab5.txt"
Write-Output "Task 11 Done"
Write-Output "Tasks Completed"

